name: Code Scanning

on:
  push:
    branches:
      - '*'

jobs:
  code_scan:
    name: Code Scanning
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Set gradlew as executable
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test


